version: "3.8"

services:
  tg-proxy:
    image: ellermister/nginx-mtproxy:latest
    container_name: tg-proxy
    environment:
      secret: $secret
      tag: $tag
      domain: "cloudflare.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./ip_white.conf:/etc/nginx/ip_white.conf"
      - "./mtp_config:/home/mtproxy/mtp_config"
