FROM ubuntu:latest
ENV JAVA_HOME="/sdk/jdk17" CLASSPATH=".:/sdk/jdk17/lib:/sdk/jdk17/jre/lib" PATH="/sdk/jdk17/bin:/sdk/jdk17/jre/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENTRYPOINT ["/sdk/jdk17/bin/java", "-jar"]
