name: "luotianyi/cloudbase:node"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          cd luotianyi/cloudbase/node
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudbase:node .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cloudbase:node

      - name: Logout hub.docker.com
        run: |
          docker logout
